
import skillImageF5001 from '@/assets/skills/f/5001.png';
import skillImageS5001 from '@/assets/skills/s/5001.png';
import skillImageF5002 from '@/assets/skills/f/5002.png';
import skillImageS5002 from '@/assets/skills/s/5002.png';
import skillImageF5003 from '@/assets/skills/f/5003.png';
import skillImageS5003 from '@/assets/skills/s/5003.png';
import skillImageF5004 from '@/assets/skills/f/5004.png';
import skillImageS5004 from '@/assets/skills/s/5004.png';
import skillImageF5005 from '@/assets/skills/f/5005.png';
import skillImageS5005 from '@/assets/skills/s/5005.png';
import skillImageF5006 from '@/assets/skills/f/5006.png';
import skillImageS5006 from '@/assets/skills/s/5006.png';
import skillImageF5007 from '@/assets/skills/f/5007.png';
import skillImageS5007 from '@/assets/skills/s/5007.png';
import skillImageF5008 from '@/assets/skills/f/5008.png';
import skillImageS5008 from '@/assets/skills/s/5008.png';

export default [{
		id: '5001',
		name: 'Claws',
		quality: 1,
		des: 'Use claws to deal 120% attack damage to the enemy',
		skillImageF: skillImageF5001,
		skillImageS: skillImageS5001,
	},
	{
		id: '5002',
		name: 'Bite',
		quality: 1,
		des: 'Deal 110% attack damage to the enemy, and continue to lose blood for 2 rounds',
		skillImageF: skillImageF5002,
		skillImageS: skillImageS5002,
	},
	{
		id: '5003',
		name: 'Strong',
		quality: 1,
		des: 'Increases defense of all teammates by 10%',
		skillImageF: skillImageF5003,
		skillImageS: skillImageS5003,
	},
	{
		id: '5004',
		name: 'Horn',
		quality: 1,
		des: 'Increases the attack power of all teammates by 10%',
		skillImageF: skillImageF5004,
		skillImageS: skillImageS5004,
	},
	{
		id: '5005',
		name: 'Roar',
		quality: 1,
		des: 'Inflicts attack damage equal to 90% of ATK to all enemies',
		skillImageF: skillImageF5005,
		skillImageS: skillImageS5005,
	},
	{
		id: '5006',
		name: 'Slam',
		quality: 1,
		des: 'Launch a slam, dealing 80% attack damage to a single enemy and stunned for 1 round',
		skillImageF: skillImageF5006,
		skillImageS: skillImageS5006,
	},
	{
		id: '5007',
		name: 'Rest',
		quality: 1,
		des: 'Restores 150 HP to self',
		skillImageF: skillImageF5007,
		skillImageS: skillImageS5007,
	},
	{
		id: '5008',
		name: 'Treat',
		quality: 1,
		des: 'Restore 100 life points to all allies',
		skillImageF: skillImageF5008,
		skillImageS: skillImageS5008,
	},
	{
		id: '5009',
		name: 'Claws',
		quality: 2,
		des: 'Use claws to deal 140% attack damage to the enemy',
		skillImageF: skillImageF5001,
		skillImageS: skillImageS5001,
	},
	{
		id: '5010',
		name: 'Bite',
		quality: 2,
		des: 'Use sharp claws to deal 120% attack damage to the enemy, and continue to lose blood for 2 rounds',
		skillImageF: skillImageF5002,
		skillImageS: skillImageS5002,
	},
	{
		id: '5011',
		name: 'Strong',
		quality: 2,
		des: 'Increases defense of all teammates by 15%',
		skillImageF: skillImageF5003,
		skillImageS: skillImageS5003,
	},
	{
		id: '5012',
		name: 'Horn',
		quality: 2,
		des: 'Increases the attack power of all teammates by 15%',
		skillImageF: skillImageF5004,
		skillImageS: skillImageS5004,
	},
	{
		id: '5013',
		name: 'Roar',
		quality: 2,
		des: 'Deals 90% attack damage to all enemies',
		skillImageF: skillImageF5005,
		skillImageS: skillImageS5005,
	},
	{
		id: '5014',
		name: 'Slam',
		quality: 2,
		des: 'Launch a slam, dealing 90% attack damage to a single enemy and stunned for 1 round',
		skillImageF: skillImageF5006,
		skillImageS: skillImageS5006,
	},
	{
		id: '5015',
		name: 'Rest',
		quality: 2,
		des: 'Restores 400 HP to self',
		skillImageF: skillImageF5007,
		skillImageS: skillImageS5007,
	},
	{
		id: '5016',
		name: 'Treat',
		quality: 2,
		des: 'Restore 200 life points to all allies',
		skillImageF: skillImageF5008,
		skillImageS: skillImageS5008,
	},

	{
		id: '5017',
		name: 'Claws',
		quality: 3,
		des: 'Use claws to deal 160% attack damage to the enemy',
		skillImageF: skillImageF5001,
		skillImageS: skillImageS5001,
	},
	{
		id: '5018',
		name: 'Bite',
		quality: 3,
		des: 'Deal 120% attack damage to the enemy, and continue to lose blood for 2 rounds',
		skillImageF: skillImageF5002,
		skillImageS: skillImageS5002,
	},
	{
		id: '5019',
		name: 'Strong',
		quality: 3,
		des: 'Increases defense of all teammates by 20%',
		skillImageF: skillImageF5003,
		skillImageS: skillImageS5003,
	},
	{
		id: '5020',
		name: 'Horn',
		quality: 3,
		des: 'Increases the attack power of all teammates by 20%',
		skillImageF: skillImageF5004,
		skillImageS: skillImageS5004,
	},
	{
		id: '5021',
		name: 'Roar',
		quality: 3,
		des: 'Inflicts attack damage equal to 100% of ATK to all enemies',
		skillImageF: skillImageF5005,
		skillImageS: skillImageS5005,
	},
	{
		id: '5022',
		name: 'Slam',
		quality: 3,
		des: 'Launch a slam, dealing 100% attack damage to a single enemy and stunned for 1 round',
		skillImageF: skillImageF5006,
		skillImageS: skillImageS5006,
	},
	{
		id: '5023',
		name: 'Rest',
		quality: 3,
		des: 'Restores HP by 60% of own attack power',
		skillImageF: skillImageF5007,
		skillImageS: skillImageS5007,
	},
	{
		id: '5024',
		name: 'Treat',
		quality: 3,
		des: 'Restores HP to all allies by 40% of their attack power',
		skillImageF: skillImageF5008,
		skillImageS: skillImageS5008,
	},
	{
		id: '5025',
		name: 'Claws',
		quality: 4,
		des: 'Use claws to deal 180% attack damage to the enemy',
		skillImageF: skillImageF5001,
		skillImageS: skillImageS5001,
	},
	{
		id: '5026',
		name: 'Bite',
		quality: 4,
		des: 'Deal 130% attack damage to the enemy, and continue to lose blood for 2 rounds',
		skillImageF: skillImageF5002,
		skillImageS: skillImageS5002,
	},
	{
		id: '5027',
		name: 'Strong',
		quality: 4,
		des: 'Increases defense of all teammates by 30%',
		skillImageF: skillImageF5003,
		skillImageS: skillImageS5003,
	},
	{
		id: '5028',
		name: 'Horn',
		quality: 4,
		des: 'Increases the attack power of all teammates by 30%',
		skillImageF: skillImageF5004,
		skillImageS: skillImageS5004,
	},
	{
		id: '5029',
		name: 'Roar',
		quality: 4,
		des: 'Inflicts attack damage equal to 120% of ATK to all enemies',
		skillImageF: skillImageF5005,
		skillImageS: skillImageS5005,
	},
	{
		id: '5030',
		name: 'Slam',
		quality: 4,
		des: 'Launch a slam, dealing 110% attack damage to a single enemy and stunned for 1 round',
		skillImageF: skillImageF5006,
		skillImageS: skillImageS5006,
	},
	{
		id: '5031',
		name: 'Rest',
		quality: 4,
		des: 'Restores HP by 80% of own attack power',
		skillImageF: skillImageF5007,
		skillImageS: skillImageS5007,
	},
	{
		id: '5032',
		name: 'Treat',
		quality: 4,
		des: 'Restores HP to all allies by 50% of their attack power',
		skillImageF: skillImageF5008,
		skillImageS: skillImageS5008,
	},
]
